# Generated by Django 5.1.3 on 2024-12-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_rename_name_user_fname_user_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme_preferences',
            field=models.ManyToManyField(related_name='theme_preferences', to='discussion.theme'),
        ),
    ]
