# Generated by Django 5.1.3 on 2024-12-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme_preferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='books_per_year',
            field=models.CharField(choices=[('0-5', '0-5'), ('5-10', '5-10'), ('10-20', '10-20'), ('20+', '20+')], default='0-5', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_themes',
            field=models.ManyToManyField(to='discussion.theme'),
        ),
    ]
