# Generated by Django 5.1.3 on 2024-12-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_remove_profile_theme_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='books_per_year',
            field=models.CharField(blank=True, choices=[('0-5', '0-5'), ('5-10', '5-10'), ('10-20', '10-20'), ('20+', '20+')], max_length=20, null=True),
        ),
    ]
