# Generated by Django 5.1.3 on 2024-12-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0006_alter_profile_books_per_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/club'),
        ),
    ]
