# Generated by Django 5.1.3 on 2024-12-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0008_alter_club_club_image_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_image',
        ),
    ]
