# Generated by Django 5.1.3 on 2024-12-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0012_bookdiscussion_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='recommendation',
            field=models.ManyToManyField(blank=True, related_name='club_rec', to='discussion.bookrecommendation'),
        ),
    ]
