# Generated by Django 5.1.3 on 2024-12-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0013_alter_club_recommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
