# Generated by Django 5.1.3 on 2024-12-09 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0014_delete_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='book_discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussion.bookdiscussion'),
        ),
    ]
